### ISSUE TITLE
Add .gitignore and remove .DS_Store files

### ISSUE THREAD

**Issue by esbeto** [Marzieh-Homayoon/react-practice#1]
Not related to React code, but it is a good practice for git projects to add a `.gitignore` file with files you don't want to track:

I see a couple of `.DS_Store` files in this repository, this type of file is used by macOS to store metadata about the directory and the files within. Usually we don't want these files on the repository.

- [x] To close this issue we should add a `.gitignore` file at the root of the project and add the following:
```
.DS_Store
```

- [x] We should also remove the `.DS_Store` files that are already committed.

**Comment by esbeto** [comment]
It is also a good idea to add the `node_modules/` folder as well to the .gitignore file

```
.DS_Store
node_modules/

```

**Comment by TasosKyr** [comment]
Minor add to Beto's comment, i would add the package-lock.json in the .gitignore file as well

**Comment by esbeto** [comment]
Fixed
